### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xu-song** [ESgame/ESgame.github.io#1]
### games

for fun
- [x] [2048](../games/2048/)
- [x] [Flappy Bird](../games/flappybird)
- [ ] [Untrusted](../games/untrusted)
- [ ] [Chome-dino]()
- [ ] [Lightbot](http://lightbot.com/) 由 http://jcf94.com/2015/11/15/2015-11-15-lightbot/ 推荐

## reference

- [有哪些很有「工程师情怀」的游戏？ | 知乎](https://www.zhihu.com/question/27535591)
- http://www.matrix67.com/blog/archives/3306
